---
- hosts: test_machine
  become: yes
  tasks:

    - name: Install Docker
      ansible.builtin.package:
        name: docker
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name:docker
        state: started
        enabled: yes

    - name: Create directory for nginx image
      ansible.builtin.file:
        path: /var/pic
        state: directory

    - name: Create directory for nginx configuration
      ansible.builtin.file:
        path: /var/nginx_conf
        state: directory
        mode: '0755'

    - name: Upload image to the remote host
      ansible.builtin.copy:
        src: ./local_image.jpg
        dest: /var/pic/image.jpg

    - name: Create custom nginx configuration in correct location
      ansible.builtin.copy:
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  root /usr/share/nginx/html/pic;
                  index image.jpg;
              }
          }
        dest: /var/nginx_conf/default.conf

    - name: Run nginx container with custom configuration
      community.docker.docker_container:
        name: nginx_container
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - /var/pic:/usr/share/nginx/html/pic
          - /var/nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
